name = "MultiGridBarrier3d"
uuid = "594ea493-0a2f-4496-9340-85da5d8e0ddf"
authors = ["Sebastien Loisel"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultiGridBarrier = "9e2c1f1d-9131-4ad4-b32f-bd2a0b0ecd1e"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.9"
FileIO = "1"
MultiGridBarrier = "0.1"
PNGFiles = "0.4"
PyCall = "1"
PyPlot = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
